apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../base
  - redis.yaml
  - minio.yaml
  - qdrant.yaml

# Local dev: dùng image local, không pull từ registry
images:
  - name: deepface_backend
    newName: deepface_backend
    newTag: 20260509-1
  - name: deepface_frontend_home
    newName: deepface_frontend_home
    newTag: latest
  - name: deepface_frontend_user
    newName: deepface_frontend_user
    newTag: latest
  - name: deepface_frontend_admin
    newName: deepface_frontend_admin
    newTag: latest

patches:
  - path: patch-no-ingress.yaml
  - path: patch-imagepullpolicy.yaml
  - path: patch-services-nodeport.yaml
  - path: patch-configmap-endpoints.yaml
