apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: deepface-qdrant-pvc
  namespace: deepface
spec:
  accessModes: ["ReadWriteOnce"]
  resources:
    requests:
      storage: 5Gi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: deepface-qdrant
  namespace: deepface
spec:
  replicas: 1
  selector:
    matchLabels:
      app: deepface-qdrant
  template:
    metadata:
      labels:
        app: deepface-qdrant
    spec:
      containers:
        - name: qdrant
          image: qdrant/qdrant:latest
          ports:
            - containerPort: 6333
            - containerPort: 6334
          volumeMounts:
            - name: storage
              mountPath: /qdrant/storage
          resources:
            requests:
              cpu: "50m"
              memory: "256Mi"
            limits:
              cpu: "800m"
              memory: "2Gi"
      volumes:
        - name: storage
          persistentVolumeClaim:
            claimName: deepface-qdrant-pvc
---
apiVersion: v1
kind: Service
metadata:
  name: deepface-qdrant
  namespace: deepface
spec:
  selector:
    app: deepface-qdrant
  ports:
    - name: http
      port: 6333
      targetPort: 6333
    - name: grpc
      port: 6334
      targetPort: 6334

