apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: deepface-redis-pvc
  namespace: deepface
spec:
  accessModes: ["ReadWriteOnce"]
  resources:
    requests:
      storage: 1Gi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: deepface-redis
  namespace: deepface
spec:
  replicas: 1
  selector:
    matchLabels:
      app: deepface-redis
  template:
    metadata:
      labels:
        app: deepface-redis
    spec:
      containers:
        - name: redis
          image: redis:7-alpine
          ports:
            - containerPort: 6379
          args: ["--appendonly", "yes"]
          volumeMounts:
            - name: data
              mountPath: /data
          resources:
            requests:
              cpu: "25m"
              memory: "64Mi"
            limits:
              cpu: "300m"
              memory: "256Mi"
      volumes:
        - name: data
          persistentVolumeClaim:
            claimName: deepface-redis-pvc
---
apiVersion: v1
kind: Service
metadata:
  name: deepface-redis
  namespace: deepface
spec:
  selector:
    app: deepface-redis
  ports:
    - name: redis
      port: 6379
      targetPort: 6379

