apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: deepface-ingress
  namespace: deepface
  annotations:
    kubernetes.io/ingress.class: nginx
spec:
  rules:
    - host: yourdomain
      http:
        paths:
          - path: /api
            pathType: Prefix
            backend:
              service:
                name: deepface-backend
                port:
                  number: 8000
          - path: /
            pathType: Prefix
            backend:
              service:
                name: deepface-frontend-home
                port:
                  number: 80
    - host: app.yourdomain
      http:
        paths:
          - path: /api
            pathType: Prefix
            backend:
              service:
                name: deepface-backend
                port:
                  number: 8000
          - path: /
            pathType: Prefix
            backend:
              service:
                name: deepface-frontend-user
                port:
                  number: 80
    - host: admin.yourdomain
      http:
        paths:
          - path: /api
            pathType: Prefix
            backend:
              service:
                name: deepface-backend
                port:
                  number: 8000
          - path: /
            pathType: Prefix
            backend:
              service:
                name: deepface-frontend-admin
                port:
                  number: 80
    # Optional: nếu bạn muốn tách riêng subdomain API
    # - host: api.yourdomain
    #   http:
    #     paths:
    #       - path: /
    #         pathType: Prefix
    #         backend:
    #           service:
    #             name: deepface-backend
    #             port:
    #               number: 8000
