apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - namespace.yaml
  - configmap.yaml
  # Apply secret separately (do not commit real secret)
  # - secret.example.yaml

  - backend.deployment.yaml
  - backend.service.yaml
  - worker.deployment.yaml

  - frontend-home.deployment.yaml
  - frontend-home.service.yaml
  - frontend-user.deployment.yaml
  - frontend-user.service.yaml
  - frontend-admin.deployment.yaml
  - frontend-admin.service.yaml

  - ingress.yaml
