server {
    listen 80;
    server_name _;
    root /usr/share/nginx/html;
    index index.html;

    location /admin/assets/ {
        alias /usr/share/nginx/html/assets/;
    }

    location /admin/ {
        try_files $uri $uri/ /index.html;
    }

    location = /admin {
        return 301 /admin/;
    }

    location / {
        try_files $uri $uri/ /index.html;
    }
}
